/*
 * Jalynn Hardin 
 * Date:3/26/2026
 * Java program about converting  American dollars to Euroes and vise versa!
 */

 import java.util.Scanner;
public class Euroes
{
{
System.out.print("Hello there,which would you prefere me to convert ");
System.out.print("Would you like me to converty ameican or Euroes for you please select options 1-2 to choose");










}





}
