/*
 * Jalynn Hardin 
 * Date:3/26/2026
 * Java program about converting  American dollars to Euroes and vise versa!
 */
import java.util.Scanner;
public class file {
public static void main(String[] args)
{

    //Main menu for choosing what to convert!
    Scanner keyboard = new Scanner(System.in);
    System.out.println("Hello there.welcome to the converter");
    System.out.println("Would you like me to convert ameican or Euroes for you please select options 1-3 to choose which one would you like me to convert for you or pick option 3 to quit out of the program");
    System.out.print("Choose an option between 1-3?");
    int option =1; 
    if(option <=1);
    System.out.println("You have chosen option 1 for converting Ameerican dollars to Euroes");
    if (option >=2);
    System.out.println("You have chosen option 2 to convert Euroes to dollars");
    double dollars = keyboard.nextDouble();
    System.out.print("What is the euroes-per dollar echange rate");

   // Converting process of american to euroes and to euroes to American dollaers!
    
    
 








   


}


  }












    





















